### ISSUE TITLE
Migrate continuous integration from CircleCI to Jenkins

### ISSUE THREAD

**Issue by rbreslow** [azavea/franklin#140]
When we [deployed](https://github.com/raster-foundry/granary/pull/39) Granary to AWS, we had to switch from CircleCI to Jenkins because we couldn't find a way to prevent secrets from being exposed in the build output.

In anticipation of https://github.com/azavea/raster-foundry-platform/issues/982, which is an issue to deploy Franklin to AWS, we decided to revisit the problem. 

A summary of our findings can be found here: https://github.com/azavea/operations/issues/425#issuecomment-597822301. The gist of it is we haven't found a great way and it would be safer to keep the Terraform output private.

To support executing Terraform within the build pipeline, we need to migrate continuous integration from CircleCI to Jenkins:

- Certain steps in `cibuild` are refactored to be executed within an OpenJDK 11 container image.
- PostgreSQL service is accessible to the SBT tests.
- Steps to execute `cibuild` and `cipublish` are encoded in a `Jenkinsfile`. 
  - Quay credentials are available to the build environment.
  - `cipublish` is gated to `master`, `release/*`, and `hotfix/*`.
  - `gh-pages` branch is ignored.
- SBT caching is considered.

**Comment by notthatbreezy** [comment]
Thanks for the writeup in the operations issue, that provides some useful context.

I have a few concerns and I would like to push back against the move to Jenkins a little bit because I think it works against some goals of the project and also maybe highlights an opportunity to handle deployment of this project in a different manner.

A few concerns about moving to Jenkins:
 - Outside contributors will not be able to see their CI results. One of the goals of this project is to be a community tool, moving CI to an area where any outside contributors won't be able to see results is a step in the wrong direction. If we are able to provision a public Jenkins instance for this purpose this goes away.
 - The isolation between jobs for Jenkins is poor - we regularly run into issues in Jenkins that are easily avoided in situations like Circle CI (for example port conflicts, having to split `cipublish` and other commands to run inside/outside `docker-compose`, etc.) This means a little more overhead for development purposes - already presented here in discussion around running `cibuild` in an OpenJDK 11 container.

An additional issue I think this highlights is whether or not the deployment code for our _internal_ instance belongs in a _public_ project. I'm worried we're going to have a `deployment/` folder hanging out here that only makes sense to someone from Azavea.

An alternative strategy for managing our deployment I think would be to have an internal process subscribe to github [release](https://developer.github.com/v3/activity/events/types/#releaseevent) events. On release events that triggers a workflow for updating our internal instance.

**Comment by rbreslow** [comment]
Thank you for bringing your perspective. I agree with the concerns you've raised. 

Do you anticipate we will need to proactively update the internal instance of Franklin? I see a path forward where we add a new container service to the raster-foundry-deployment repository and manage releases with a `franklin_version` variable, similar to how we handle Metabase.

> An additional issue I think this highlights is whether or not the deployment code for our _internal_ instance belongs in a _public_ project. I'm worried we're going to have a `deployment/` folder hanging out here that only makes sense to someone from Azavea.

This is a good point. If the deployment needs to be coupled with the release cycle of the open source project, I think we should split things out into a franklin-deployment repository.

Determining what wakes up the deployment process (whether manually, with a GitHub release event, etc) can be thought about after https://github.com/azavea/raster-foundry-platform/issues/982 is completed.

The pattern we decide on here will likely be replicated for future open source projects that have their own pipeline, but connect to another pipeline that manages a release/deployment process. I surfaced this to make sure we decide on something we'd be comfortable using elsewhere.

**Comment by notthatbreezy** [comment]
> Do you anticipate we will need to proactively update the internal instance of Franklin?

Yeah I think we will want to keep it up to date. I’m not sure what the right cadence here will be though. If it could be every time there’s a commit on master that would be perfect. I think alternatively every new tag would be good too.

This repository follows a different pattern and merges to master to try and approach continuous delivery, but I think focusing on commits to master or releases would also work for other git flow repos of ours.
