### ISSUE TITLE
"DecodingFailure" when importing Sentinel-5P on AWS Open Data

### ISSUE THREAD

**Issue by danielklim** [azavea/franklin#323]
**Describe the bug**
Attempted to import STAC catalog for the [Sentinel-5P dataset on AWS Open Data](https://meeo-s5p.s3.amazonaws.com/catalog.json). On the first attempt, received the following error:

- "Exception in thread "main" com.amazonaws.SdkClientException: Unable to find a region via the region provider chain. Must provide an explicit region in the builder or setup environment to supply a region."

Based on AWS Java SDK docs, added the ENV variable `AWS_REGION=eu-central-1`. On that attempt, received the following error:

- DecodingFailure(Attempt to decode value on failed cursor, List(DownField(stac_extensions)))

**Expected behavior**
STAC catalog imports successfully instead of erroring.

**Comment by jisantuc** [comment]
Thanks @danielklim -- the decoding failure issue is upstream in stac4s, and is tracked here: https://github.com/azavea/stac4s/issues/121. Short version, we made a field required in the software that isn't required in the spec 🤦‍♂️.

However, after that fix, it will still be challenging to import the Sentinel-5P dataset, since it's from an earlier STAC version than what Franklin is capable of importing. One difference that will cause a problem is that the shape of assets has changed considerably since 0.7.0. We haven't yet figured out how to safely handle several versions simultaneously.

**Comment by danielklim** [comment]
Thanks for the quick response! Understood, and will keep an eye on the project for supporting older specs. Please let me know if I can be of any assistance in the meantime with testing, feedback, etc.

**Comment by jisantuc** [comment]
Sounds good, thanks for offering to help out! Since STAC itself is just about to 1.0 (🤞 that the prospect of stability pays off), supporting older versions isn't very high on our priority list. You can track progress toward 1.0 on a few milestones in the STAC repo -- https://github.com/radiantearth/stac-spec/milestones

That said, figuring out STAC version migration and a zoo of public STACs for testing purposes is something that I'm pretty interested in -- if you want to have a conversation about that, what you're up to in STAC, or any other issues you run into in Franklin, feel free to pop by our [gitter channel](https://gitter.im/franklin-stac/community)

**Comment by jisantuc** [comment]
Once I get a STAC4S release out, the initial decoding failure you ran into should be fixed here, and you should be able to run into the later errors I mentioned -- I'll keep this open until I verify that

**Comment by jisantuc** [comment]
stac4s was upgraded a few days ago, and the catalog now correctly decodes, which brings us to a second big hurdle for the Sentinel-5P data (in addition to the old STAC version) -- Franklin doesn't yet know how to read http catalogs. #259 already addresses adding that capability, so I'll close this. Thanks for this issue, and let us know if you run into other problems!
