### ISSUE TITLE
Franklin CLI hangs indefinitely

### ISSUE THREAD

**Issue by rbreslow** [azavea/franklin#545]
e.g. run migrations, import a STAC catalog. The process will never exit.

**Comment by jisantuc** [comment]
This isn't just here -- we've had similar issues in raster-foundry/gkeeper. I'm not certain whether we have the same problem in Granary. I will test that out and see if we're doing anything special there.

**Comment by jisantuc** [comment]
Oh, in Granary we use the Flyway container for running migrations, so it's not comparable. Nevermind the Granary comparison comment. Anyway, this is happening in enough places that it's probably worth figuring out. The list of places I know it occurs is:

- Franklin
- gkeeper
- conveyor

I'd assumed for a while it was because my machine is cursed but that seems not to be the case.
