### ISSUE TITLE
Postgres + Postgis versions supported: does Franklin support Postgres9.6 + Postgis2.3 ? 

### ISSUE THREAD

**Issue by adrienDog** [azavea/franklin#659]
Hello,

I didnt find a link to a public slack or gitter, sorry if here is not the best place to ask.

We are trying to use a managed Postgres instance on Google Cloud Platform. Unfortunately, the latest Postgis version they support is `2.3.11` which can be installed only on Postgres `9.6` latest.

I have tried running Franklin locally with [2.3-postgres9.6-slim](https://quay.io/repository/azavea/postgis?tab=tags) and was able to run migrations, import collection + features.

Can Franklin work with Postgres9.6+Postgis2.3.11? Here is the [feature matrix](https://www.postgresql.org/about/featurematrix/)

thank you very much for your help,

**Comment by jisantuc** [comment]
👋 The only issue I'm aware of with those versions is that you won't have access to the MVT functions, e.g. 

- `ST_TileEnvelope` since 3.0 https://postgis.net/docs/ST_TileEnvelope.html
- `ST_AsMVT` since 2.4 https://postgis.net/docs/ST_AsMVT.html

This means if you're running with the `--with-tiles` flag, the vector tile routes will fail at runtime.

I am a little confused though -- the PostGIS section of cloud sql docs says they support 3.0+ -- https://cloud.google.com/sql/docs/postgres/extensions#postgis. Is this different from what you're using?

Also you can find out public gitter here -- https://gitter.im/franklin-stac/community. There's a badge in the README but I just learned that it's an image instead of text 🤦🏻‍♂️

![image](https://user-images.githubusercontent.com/5702984/114037924-a6dfa100-983e-11eb-8d7c-90e075689cb3.png)

**Comment by adrienDog** [comment]
Hi James! Thanks a lot for your quick and thorough response :)

Indeed they support Postgis 3.0 but I thought it wouldn't work with Franklin for some reason. Maybe because the `docker-compose` from the documentation points to `2.5-postgres11.4-slim`.

**Comment by jisantuc** [comment]
Here's what I have locally via the docker-compose.yml file in the dev setup:

```
franklin=# select version();
                                                     version
------------------------------------------------------------------------------------------------------------------
 PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
(1 row)

franklin=# select postgis_version();
            postgis_version
---------------------------------------
 3.0 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
(1 row)
```

I'll update the docs to match. Relatedly, we're eagerly awaiting managed postgresql services with postgis 3.1 support and will expect to upgrade dev / docs once that's widely available -- https://rmr.ninja/2020-11-19-waiting-for-postgis-3-1-mvt/

**Comment by adrienDog** [comment]
ah great! thanks a lot James, I will try these ones on our terraform right away :) thanks for the help probably we can close the issue. next time I will ask on the gitter, I should have seen the badge sorry about that
